name: Terraform Pipeline

on:
  push:
    branches:
      - main         # run automatically when you push to main
  pull_request:       # run when a PR is opened
  workflow_dispatch:  # allows manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: day-3-statefile   # 👈 your Terraform folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # Optional: Apply (manual trigger only)
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
